<?php $this->headTitle('Produtos'); ?>

<h1>Produtos</h1>

<?php echo $this->form()->openTag($this->form->setAttribute('action', $this->url('admin.products.create'))); ?>

<?php echo $this->formLabel($this->form->get('name')); ?>
<?php echo $this->formElement($this->form->get('name')); ?>

<?php echo $this->formLabel($this->form->get('price')); ?>
<?php echo $this->formElement($this->form->get('price')); ?>

<?php echo $this->formLabel($this->form->get('description')); ?>
<?php echo $this->formElement($this->form->get('description')); ?>

<?php echo $this->formElement($this->form->get('submit')->setLabel('Cadastrar')); ?>

<?php echo $this->form()->closeTag(); ?>

<ul>
  <?php foreach ($this->products as $product) : ?>
  <li><?php echo $product->name; ?></li>
  <?php endforeach; ?>
</ul>